services:
  mongo:
    image: mongo
    ports:
      - "27017:27017"
  ocr-rest:
    build:
      context: .
    ports:
      - "8080:8080"
    environment:
      - LC_ALL=C
      - TESSDATA_PREFIX=/usr/local/share/tessdata
    depends_on:
      - mongo
    links:
      - mongo  
